import{a as m,S as f,i}from"./assets/vendor-CsOP1TRZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const p="51878894-a5638140813a030bb43789a30",y="https://pixabay.com/api/",g=async s=>{const o={key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await m.get(y,{params:o})).data.hits}catch{throw new Error("Unable to fetch images")}},d=document.querySelector(".gallery");let h=new f(".gallery a");const L=s=>{const o=s.map(({webformatURL:t,largeImageURL:n,tags:e})=>`
    <a href="${n}">
      <img src="${t}" alt="${e}" />
    </a>
  `).join("");d.insertAdjacentHTML("beforeend",o),h.refresh()},b=()=>{d.innerHTML=""},q=()=>{document.body.classList.add("loading")},v=()=>{document.body.classList.remove("loading")},c=document.querySelector(".form"),w=c.elements["search-text"];c.querySelector('button[type="submit"]');const u=document.querySelector("main"),l=document.createElement("div");l.id="loader";l.innerHTML=`
  <div class="spinner"></div>
  <span>Loading images, please wait...</span>
`;u.insertBefore(l,u.firstChild);c.addEventListener("submit",async s=>{s.preventDefault();const o=w.value.trim();if(o===""){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}b(),q();try{const t=await g(o);if(!t||t.length===0){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t)}catch(t){i.error({title:"Error",message:t.message,position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
